In [8]:
import numpy as np
x = np.array([1,2,3,4,5,6])
y = np.array([5.5,6.5,7.5,8.5,9.5,10.5])
print(x,y)
print(x + y)
print('add',np.add(x,y))
print(x - y)
print('sub',np.subtract(x,y))
print(x * y)
print('multi',np.multiply(x,y))
print(x / y)
print('div',np.divide(x,y))

[1 2 3 4 5 6] [ 5.5  6.5  7.5  8.5  9.5 10.5]
[ 6.5  8.5 10.5 12.5 14.5 16.5]
add [ 6.5  8.5 10.5 12.5 14.5 16.5]
[-4.5 -4.5 -4.5 -4.5 -4.5 -4.5]
sub [-4.5 -4.5 -4.5 -4.5 -4.5 -4.5]
[ 5.5 13.  22.5 34.  47.5 63. ]
multi [ 5.5 13.  22.5 34.  47.5 63. ]
[0.18181818 0.30769231 0.4        0.47058824 0.52631579 0.57142857]
div [0.18181818 0.30769231 0.4        0.47058824 0.52631579 0.57142857]


In [19]:
import numpy as np
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
print(x,y)
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[[1 2]
 [3 4]] [[5.5 6.5]
 [7.5 8.5]]
[[ 6.5  8.5]
 [10.5 12.5]]
[[-4.5 -4.5]
 [-4.5 -4.5]]
[[ 5.5 13. ]
 [22.5 34. ]]
[[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [21]:
x = np.array([1,2,3,4])
print(x)
print('exe',np.exp(x))
print('SQRT',np.sqrt(x))
print('POW',np.power(x,3))

[1 2 3 4]
exe [ 2.71828183  7.3890561  20.08553692 54.59815003]
SQRT [1.         1.41421356 1.73205081 2.        ]
POW [ 1  8 27 64]


In [32]:
x = np.array([[1,2],[3,4]])
print(x)
print('all avg',x.mean())
print('column avg',x.mean(axis=0))
print('row avg',x.mean(axis=1))
print('all sum',x.sum())
print('column sum',x.sum(axis=0))
print('row sum',x.sum(axis=1))
print('all std',x.std())
print('column std',x.std(axis=0))
print('row std',x.std(axis=1))
#median is different
print('all med',np.median(x))
print('column med',np.median(x,axis=0))
print('row med',np.median(x,axis=1))
print('all max',x.max())
print('column max',x.max(axis=0))
print('row max',x.max(axis=1))
print('all min',x.min())
print('column min',x.min(axis=0))
print('row min',x.min(axis=1))

[[1 2]
 [3 4]]
all avg 2.5
column avg [2. 3.]
row avg [1.5 3.5]
all sum 10
column sum [4 6]
row sum [3 7]
all std 1.118033988749895
column std [1. 1.]
row std [0.5 0.5]
all med 2.5
column med [2. 3.]
row med [1.5 3.5]
all max 4
column max [3 4]
row max [2 4]
all min 1
column min [1 2]
row min [1 3]


In [35]:
x = np.array([[1,2],[3,4]])
print(x)
print(x + 3)
print(x - 3)
print(x * 3)
print(x / 3)

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [38]:
x = np.array([1,2,3])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
z = np.array([1,2,3]).reshape(3,1)
print(x)
print(y)
print(z)
print('x+y',x + y)
print('y+z',y + z)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
x+y [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
y+z [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [40]:
x = np.full((4,4),1)*[1,2,3,4]
print(x)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [42]:
x = np.ones((4,4))*np.arange(1,5)
print(x)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
