In [4]:
import numpy as np
x = np.array([[1,2,3,],[4,5,6],[7,8,9]])
print(x)
print(x[0,0],x[0,1],x[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 9


In [7]:
x = [1,2,3,4,5,6,9]
x[3] = 20
print(x)

[1, 2, 3, 20, 5, 6, 9]


In [9]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('original',x)
x[0,0] = 20
print('changed',x)

original [[1 2 3]
 [4 5 6]
 [7 8 9]]
changed [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [11]:
x = np.array([1,2,3,4,5,6,7,8])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('original x',x)
x = np.delete(x,[0,4])
#first row, the fifth element
print('modified x',x)
print('original y',y)
y = np.delete(y,0,axis=0)
#the first row
print('modified y',y)

original x [1 2 3 4 5 6 7 8]
modified x [2 3 4 6 7 8]
original y [[1 2 3]
 [4 5 6]
 [7 8 9]]
modified y [[4 5 6]
 [7 8 9]]


In [22]:
x = np.append(x,6)
print('append x',x)
x = np.append(x,[7,8])
print('append 2 x',x)
v = np.append(y,[[10,11,12]],axis=0)
print('append y', v)
w = np.append(y,[[13],[14]],axis=1)
print('append y',w)

append x [2 3 4 6 7 8 6 6 7 8 6 7 8 6 7 8 6 7 8 6 7 8 6]
append 2 x [2 3 4 6 7 8 6 6 7 8 6 7 8 6 7 8 6 7 8 6 7 8 6 7 8]
append y [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
append y [[ 4  5  6 13]
 [ 7  8  9 14]]


In [24]:
x = np.insert(x,2,[3,4])
#insert infront of the 3rd element
print('insert',x)
y = np.insert(y,1,[2,2,2],axis=0)
#insert infront of 2nd row
print('insert',y)

insert [2 3 3 4 3 4 4 6 7 8 6 6 7 8 6 7 8 6 7 8 6 7 8 6 7 8 6 7 8]
insert [[4 5 6]
 [2 2 2]
 [7 8 9]]
