In [4]:
import numpy as np
x = np.array([1,2,3,4,5,6])
y = np.array([4,6,3,7,2,6])
print(x,y)
print('in both',np.intersect1d(x,y))
print('in x not y',np.setdiff1d(x,y))
print('all in x & y',np.union1d(x,y))

[1 2 3 4 5 6] [4 6 3 7 2 6]
in both [2 3 4 6]
in x not y [1 5]
all in x & y [1 2 3 4 5 6 7]


In [16]:
x = np.random.randint(1,11,size = (10,))
print('original x',x)
print('sort',np.sort(x))
print('after sort x',x)
#sort()would not change the original
x.sort()
print(x)
# sort in place,changed the original

original x [ 9  1  6  4  2  3 10  8  9  5]
sort [ 1  2  3  4  5  6  8  9  9 10]
after sort x [ 9  1  6  4  2  3 10  8  9  5]
[ 1  2  3  4  5  6  8  9  9 10]


In [18]:
x = np.random.randint(1,11,size = (5,5))
print('original x',x)
print('column',np.sort(x,axis=0))
print('rows',np.sort(x,axis=1))

original x [[ 4  9  5  1 10]
 [ 2  6  8  1  4]
 [ 6  7  1  6  9]
 [ 7  5 10  1  9]
 [ 7  3  5  4  3]]
column [[ 2  3  1  1  3]
 [ 4  5  5  1  4]
 [ 6  6  5  1  9]
 [ 7  7  8  4  9]
 [ 7  9 10  6 10]]
rows [[ 1  4  5  9 10]
 [ 1  2  4  6  8]
 [ 1  6  6  7  9]
 [ 1  5  7  9 10]
 [ 3  3  4  5  7]]


In [20]:
x = np.random.randint(1,26,size = (5,5))
y = x[x%2 == 1]
print(x)
print(y)

[[19 13  2 25  9]
 [ 5 22 16  6 10]
 [23  3  8 21 15]
 [14 15 18 24  2]
 [ 7 15 11  7 18]]
[19 13 25  9  5 23  3 21 15 15  7 15 11  7]
