In [16]:
import numpy as np
x = np.arange(20).reshape(4,5)
print('original x\n',x)

original x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
z = x[1:4,2:5]
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [8]:
w = x[1:,2:5]
print(w)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [10]:
v = x[:3,2:5]
print(v)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [13]:
q = x[:,2]
print(q)
#the third column, but give a row

[ 2  7 12 17]


In [17]:
r = x[:,2:3]
print(r)
#the third colum, but return each row

[[ 2]
 [ 7]
 [12]
 [17]]


In [21]:
x = np.array([1,2])
y = np.array([[3,4],[5,6]])
z = np.vstack((x,y))
print('x',x)
print('y',y)
print('z',z)
w = np.hstack((y,x.reshape(2,1)))
print('w',w)

x [1 2]
y [[3 4]
 [5 6]]
z [[1 2]
 [3 4]
 [5 6]]
w [[3 4 1]
 [5 6 2]]


In [23]:
x = np.arange(20).reshape(4,5)
print('original x\n',x)
z = x[1:4,2:5]
print('z',z)
z[2,2] = 555
print('x',x)
#z is a reflection of x, change z, x will change as well

original x
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
z [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
x [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]


In [24]:
x = np.arange(20).reshape(4,5)
print('original x',x)
z = np.copy(x[1:4,2:5])
print('z',z)
w = x[1:4,2:5].copy()
print('w',w)

original x [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
z [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
w [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
