In [3]:
import numpy as np
x = np.zeros((3,4))
print(x)
print(type(x))
print(x.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
float64


In [7]:
y = np.ones((3,5))
print(y)
print(type(y))
print(y.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64


In [9]:
z = np.full((3,5),4)
print(z)
print(type(z))
print(z.dtype)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
<class 'numpy.ndarray'>
int64


In [11]:
k = np.eye(6)
print(k)
print(type(k))
print(k.dtype)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
float64


In [12]:
d = np.diag([34,25,34,3,0,6])
print(d)
print(type(d))
print(d.dtype)

[[34  0  0  0  0  0]
 [ 0 25  0  0  0  0]
 [ 0  0 34  0  0  0]
 [ 0  0  0  3  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  6]]
<class 'numpy.ndarray'>
int64
