In [3]:
import numpy as np
y = np.arange(20).reshape(4,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
z = np.random.random((3,4))
print(z)

[[0.2358459  0.1639299  0.67584776 0.39467726]
 [0.06753666 0.45301615 0.63695793 0.98846033]
 [0.57021661 0.44348839 0.5450706  0.15166669]]


In [7]:
x = np.random.randint(4,10,size=(3,2))
print(x)

[[4 5]
 [6 5]
 [7 6]]


In [10]:
n = np.random.normal(0,0.1,size=(30,40))
print(n)
print(n.mean())
print(n.max())
print(n.min())
print('n has', (n<0).sum(),'negative numbers')
print('n has', (n>0).sum(),'positive numbers')

[[-1.60716595e-02  4.24298828e-02  8.43868343e-02 ... -1.13868393e-01
   1.54583098e-01  5.54649754e-02]
 [-1.18151232e-02  2.81126528e-02  3.74159564e-03 ...  1.39586576e-01
  -7.83555367e-02 -1.48199132e-01]
 [-4.70624814e-02  1.28769753e-01  8.74307983e-02 ... -8.13856022e-02
  -2.41408996e-01  9.31282420e-02]
 ...
 [ 1.57018838e-01  1.45155618e-01 -2.39925222e-04 ... -1.07625192e-01
   2.63509175e-02 -1.64191420e-01]
 [-1.28827335e-01 -3.03095995e-01 -3.22998925e-02 ...  4.22841993e-02
  -3.51502721e-02  8.99905711e-02]
 [-5.04197633e-02 -4.27594362e-02  6.64737092e-02 ... -4.19399255e-02
  -1.27100012e-02 -1.78503106e-01]]
-0.0008608707120822967
0.3385933499695364
-0.303095994856593
n has 597 negative numbers
n has 603 positive numbers
