In [2]:
import numpy as np
x = np.arange(20).reshape(4,5)
print('x',x)
indices = np.array([1,3])
# 1rank array as indices
y = x[indices,:]
z = x[:,indices]
print('y',y)
print('z',z)

x [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
y [[ 5  6  7  8  9]
 [15 16 17 18 19]]
z [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [5]:
x = np.arange(25).reshape(5,5)
print('x',x)
print('y',np.diag(x))
print('z',np.diag(x,k=1))
print('w',np.diag(x,k=-1))

x [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
y [ 0  6 12 18 24]
z [ 1  7 13 19]
w [ 5 11 17 23]


In [13]:
x = np.array([[1,2,3],[4,5,6],[2,5,6]])
print(x)
print('unique',np.unique(x))

[[1 2 3]
 [4 5 6]
 [2 5 6]]
unique [1 2 3 4 5 6]


In [16]:
x = np.arange(25).reshape(5,5)
print('x',x)
print(x[x > 10])
print(x[x <= 7])
print(x[(x > 10)&(x < 17)])
x[(x > 10) & (x < 17)] = -1
print(x)

x [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7]
[11 12 13 14 15 16]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]
