In [3]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print('x has dimensions of:',x.shape)
print('x is an object of type:',type(x))

[1 2 3 4 5]
x has dimensions of: (5,)
x is an object of type: <class 'numpy.ndarray'>


In [5]:
x = np.array(['Hello',1,2])
print(x)
print('x has dimensions of:',x.shape)
print('x is an object of type:',type(x))

['Hello' '1' '2']
x has dimensions of: (3,)
x is an object of type: <class 'numpy.ndarray'>


In [12]:
y = np.array([[1,2,3],[4,5,5],[7,8,9],[4,10,11]])
print('y=\n',y)
print('y has dimension:',y.shape)
print('y has a total of:',y.size,'elements')
print('y is an object of type:',type(y))
print('the element are of type:',y.dtype)

y=
 [[ 1  2  3]
 [ 4  5  5]
 [ 7  8  9]
 [ 4 10 11]]
y has dimension: (4, 3)
y has a total of: 12 elements
y is an object of type: <class 'numpy.ndarray'>
the element are of type: int64


In [14]:
x = np.array([1.5,2.2,3,5,6],dtype=np.int64)
print(x)
print(x.dtype)

[1 2 3 5 6]
int64
