In [5]:
import numpy as np
x = np.arange(10)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
<class 'numpy.ndarray'>
int64


In [7]:
x = np.arange(4,10)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[4 5 6 7 8 9]
(6,)
<class 'numpy.ndarray'>
int64


In [9]:
x = np.arange(3,10,2)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[3 5 7 9]
(4,)
<class 'numpy.ndarray'>
int64


In [13]:
x = np.linspace(0,25,10)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
(10,)
<class 'numpy.ndarray'>
float64


In [12]:
x = np.linspace(0,25,10,endpoint = False)
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
(10,)
<class 'numpy.ndarray'>
float64
